# Generated by Django 2.0.dev20170919140901 on 2017-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.CharField(max_length=200)),
                ('word_name', models.CharField(max_length=200)),
                ('word_phonetic', models.CharField(max_length=200)),
                ('word_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
